#!/usr/bin/env bash
# Resolve host publish ports for docker compose.
# Prefers values from the environment / .env; if a preferred port is already
# bound on the host (or already claimed in this run), bumps until a free one
# is found (preferred .. preferred+99).
#
# Usage:
#   source scripts/allocate-ports.sh
#   # exports POSTGRES_HOST_PORT, ADMINER_PORT, PORT

set -euo pipefail

_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Read a single KEY=value from .env without sourcing the whole file (avoids
# breaking on unquoted spaces/secrets unrelated to ports).
_read_dotenv() {
  local key="$1"
  local file="${_ROOT_DIR}/.env"
  [[ -f "$file" ]] || return 0
  local line
  line="$(grep -E "^[[:space:]]*${key}=" "$file" | tail -n 1 || true)"
  [[ -n "$line" ]] || return 0
  local val="${line#*=}"
  val="${val#"${val%%[![:space:]]*}"}"
  val="${val%"${val##*[![:space:]]}"}"
  val="${val#\"}"
  val="${val%\"}"
  val="${val#\'}"
  val="${val%\'}"
  printf '%s' "$val"
}

_env_or_dotenv() {
  local key="$1"
  local default="$2"
  local from_env="${!key-}"
  if [[ -n "${from_env}" ]]; then
    printf '%s' "$from_env"
    return
  fi
  local from_file
  from_file="$(_read_dotenv "$key")"
  if [[ -n "$from_file" ]]; then
    printf '%s' "$from_file"
    return
  fi
  printf '%s' "$default"
}

_USED_PORTS=()

_port_in_use() {
  local port="$1"

  for claimed in "${_USED_PORTS[@]+"${_USED_PORTS[@]}"}"; do
    if [[ "$claimed" == "$port" ]]; then
      return 0
    fi
  done

  if command -v lsof >/dev/null 2>&1; then
    if lsof -nP -iTCP:"${port}" -sTCP:LISTEN >/dev/null 2>&1; then
      return 0
    fi
  fi

  if command -v docker >/dev/null 2>&1; then
    if docker ps --format '{{.Ports}}' 2>/dev/null | grep -Eq "(^|[, ])([0-9.]*:)?${port}->"; then
      return 0
    fi
  fi

  # Bind probe as a final check (covers listeners lsof/docker may miss).
  if command -v python3 >/dev/null 2>&1; then
    if ! python3 - "$port" <<'PY'
import socket, sys
port = int(sys.argv[1])
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
try:
    s.bind(("0.0.0.0", port))
except OSError:
    sys.exit(1)
finally:
    s.close()
sys.exit(0)
PY
    then
      return 0
    fi
  fi

  return 1
}

_allocate_port() {
  local name="$1"
  local preferred="$2"
  local port="$preferred"
  local max=$((preferred + 99))

  while _port_in_use "$port"; do
    if (( port >= max )); then
      echo "error: could not find a free host port for ${name} near ${preferred}" >&2
      return 1
    fi
    port=$((port + 1))
  done

  _USED_PORTS+=("$port")

  if (( port != preferred )); then
    echo "port: ${name} preferred ${preferred} is busy → using ${port}" >&2
  fi

  echo "$port"
}

_preferred_postgres="$(_env_or_dotenv POSTGRES_HOST_PORT "$(_env_or_dotenv POSTGRES_PORT 5432)")"
_preferred_adminer="$(_env_or_dotenv ADMINER_PORT 8080)"
_preferred_backend="$(_env_or_dotenv PORT 3007)"

POSTGRES_HOST_PORT="$(_allocate_port POSTGRES_HOST_PORT "${_preferred_postgres}")"
ADMINER_PORT="$(_allocate_port ADMINER_PORT "${_preferred_adminer}")"
PORT="$(_allocate_port PORT "${_preferred_backend}")"

export POSTGRES_HOST_PORT ADMINER_PORT PORT

# Persist for follow-up tools / `docker compose` in this project root.
cat > "${_ROOT_DIR}/.env.docker.ports" <<EOF
# Auto-generated by scripts/allocate-ports.sh — do not edit.
# Host publish ports for the current docker compose stack.
POSTGRES_HOST_PORT=${POSTGRES_HOST_PORT}
ADMINER_PORT=${ADMINER_PORT}
PORT=${PORT}
EOF

echo "host ports: postgres=${POSTGRES_HOST_PORT} adminer=${ADMINER_PORT} backend=${PORT}" >&2
